apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespace }}
  labels:
    io.kompose.service: {{ .Values.pygeoapi.name }}
  name: {{ .Values.pygeoapi.service_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.pygeoapi.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.pygeoapi.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
      containers:
      - env:
        - name: PYGEOAPI_SERVER_URL
          value: {{ .Values.pygeoapi.config.server.url }}
        {{ if .Values.pygeoapi.iam_realm }}
        - name: EOEPCA_REGISTRATION_API_IAM_REALM
          value: {{ .Values.pygeoapi.iam_realm }}
        {{ end }}
        {{ if .Values.pygeoapi.iam_grant_type }}
        - name: EOEPCA_REGISTRATION_API_IAM_GRANT_TYPE
          value: {{ .Values.pygeoapi.iam_grant_type }}
        {{ end }}
        {{ if .Values.pygeoapi.iam_endpoint }}
        - name: EOEPCA_REGISTRATION_API_IAM_ENDPOINT
          value: {{ .Values.pygeoapi.iam_endpoint }}
        {{ end }}
        - name: CONTAINER_PORT
          value: "{{ .Values.pygeoapi.container_port }}"
        image: {{ .Values.pygeoapi.image.repository }}:{{ .Values.pygeoapi.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.pygeoapi.image.pullPolicy }}
        name: pygeoapi
        {{ if .Values.pygeoapi.secret.name }}
        envFrom:
        - secretRef:
            name: {{ .Values.pygeoapi.secret.name }}
        {{ end }}
        ports:
        - containerPort: {{ .Values.pygeoapi.container_port }}
        resources: {}
        volumeMounts:
        - mountPath: {{ .Values.pygeoapi.volume_path }}
          name: {{ .Values.pygeoapi.volume_name }}
      restartPolicy: Always
      volumes:
      - name: {{ .Values.pygeoapi.volume_name }}
        configMap:
          name: {{ .Values.pygeoapi.configmap_name }}
