{{ if .Values.iam.identityApi.enabled -}}
{{ if .Values.iam.identityApi.createRoute -}}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: identity-api-route
spec:
  http:
  - name: identity-api
    match:
      hosts: {{- .Values.iam.identityApi.hosts | toYaml | nindent 6 }}
      paths: {{- .Values.iam.identityApi.paths | toYaml | nindent 6 }}
    backends:
      - serviceName: identity-api
        servicePort: 8080
    plugins:
      - name: openid-connect
        enable: false
        config:
{{- if .Values.iam.identityApi.clientId }}
          client_id: {{ .Values.iam.identityApi.clientId | quote }}
{{- end }}
          access_token_in_authorization_header: true
          use_jwks: true
          discovery: {{ printf "%s/realms/%s/.well-known/openid-configuration" .Values.iam.keycloak.url .Values.iam.keycloak.configuration.realm.name | quote }}
        secretRef: {{ .Values.iam.identityApi.clientSecretRef | default "identity-api-route" | quote }}
      - name: authz-keycloak
        enable: true
        config:
{{- if .Values.iam.identityApi.clientId }}
          client_id: {{ .Values.iam.identityApi.clientId | quote }}
{{- end }}
          discovery: {{ printf "%s/realms/%s/.well-known/uma2-configuration" .Values.iam.keycloak.url .Values.iam.keycloak.configuration.realm.name | quote }}
          lazy_load_paths: true
          # ssl_verify may have to be set to false in a test environment. Not recommended for production.
          ssl_verify: false
        secretRef: {{ .Values.iam.identityApi.clientSecretRef | default "identity-api-route" | quote }}
{{- end }}
{{- end }}